"""Data schemas for the API."""

from typing import Dict, Optional

from pydantic import BaseModel, Field


class AgentRequest(BaseModel):
    """
    Schema for agent requests.

    This class defines the structure for incoming requests to AI agents,
    containing the user query that needs to be processed.

    Attributes:
        query: The text query or question sent to the agent for processing.
        llm_provider: The specific AI model or agent to be used for processing the query

    Example:
        ```python
        request = AgentRequest(query="What is the capital of France?", llm="openai")
        ```
    """

    query: str = Field(..., description="Query or question for the agent")
    llm_provider: Optional[str] = Field(
        default="openai",
        description="Agent to be used for processing the query",
    )


class TokenUsage(BaseModel):
    """
    Structure for token usage.

    This class tracks the usage metrics for AI model interactions,
    specifically focusing on token consumption for billing and monitoring.

    Attributes:
        requests: Number of API requests made to the model.
        request_tokens: Count of tokens used in the input/prompt.
        response_tokens: Count of tokens generated in the model's response.
        total_tokens: Sum of request and response tokens.

    Example:
        ```python
        usage = TokenUsage(
            requests=1,
            request_tokens=15,
            response_tokens=45,
            total_tokens=60
        )
        ```
    """

    requests: int = Field(0, description="Number of requests made")
    request_tokens: int = Field(0, description="Tokens used in the input")
    response_tokens: int = Field(0, description="Tokens used in the response")
    total_tokens: int = Field(0, description="Total tokens used")


class AgentResponse(BaseModel):
    """
    Schema for agent responses.

    This class defines the structure for responses returned by AI agents,
    including the generated text, token usage statistics, and additional metadata.

    Attributes:
        response: The text response generated by the agent.
        usage: Token usage statistics for the interaction.
        metadata: Additional information about the response, such as model used,
                 generation parameters, or other context.

    Example:
        ```python
        response = AgentResponse(
            response="Paris is the capital of France.",
            usage=TokenUsage(request_tokens=10, response_tokens=8, total_tokens=18),
            metadata={"model": "gpt-4o-mini", "temperature": 0.7}
        )
        ```
    """

    response: str = Field(..., description="Response from the agent")
    usage: TokenUsage = Field(default=None, description="Agent usage in the query")
    metadata: Optional[Dict] = Field(
        default=None, description="Additional metadata for the response"
    )
