"""Data schemas for the API."""

from typing import List, Literal, Optional

from pydantic import BaseModel, Field
from pydantic_ai.messages import ModelMessage
from pydantic_ai.usage import Usage


class AgentRequest(BaseModel):
    """
    Schema for agent requests.

    This class defines the structure for incoming requests to AI agents,
    containing the user query that needs to be processed.

    Attributes:
        query: The text query or question sent to the agent for processing.
        history: Optional list of previous messages exchanged with the agent,
                providing context for the current query.
        llm_provider: The specific AI model or agent to be used for processing the query

    Example:
        ```python
        request = AgentRequest(query="What is the capital of France?", llm="openai")
        ```
    """

    query: str = Field(..., description="Query or question for the agent")
    history: Optional[List[ModelMessage]] = Field(
        default=None,
        description="History of previous messages for context",
    )
    llm_provider: Optional[Literal["openai", "gemini", "ollama"]] = Field(
        default="openai",
        description="Agent to be used for processing the query",
    )


class AgentResponse(BaseModel):
    """
    Schema for agent responses.

    This class defines the structure for responses returned by AI agents,
    including the generated text, token usage statistics, and additional metadata.

    Attributes:
        response: The text response generated by the agent.
        usage: Token usage statistics for the interaction.
        history: List of messages exchanged during the interaction.

    Example:
        ```python
        response = AgentResponse(
            response="Paris is the capital of France.",
            usage=TokenUsage(request_tokens=10, response_tokens=8, total_tokens=18),
            metadata={"model": "gpt-4o-mini", "temperature": 0.7}
        )
        ```
    """

    response: str = Field(..., description="Response from the agent")
    usage: Usage = Field(default=None, description="Agent usage in the query")
    history: Optional[List[ModelMessage]] = Field(
        default=None, description="History of messages exchanged"
    )
